#!/bin/sh
export PATH=/sbin:/bin:/usr/sbin:/usr/bin
mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs none /dev

mkdir -p /mnt/userdata
i=0
while [ $i -lt 10 ]; do
  mount -t ext4 /dev/block/by-name/userdata /mnt/userdata 2>/dev/null && break
  sleep 1; i=$((i+1))
done

mkdir -p /mnt/rootfs
losetup -f /mnt/userdata/adilos/adilos-rootfs.img
LOOP=$(losetup -a | grep adilos-rootfs.img | cut -d: -f1 | head -n1)
mount -t ext4 $LOOP /mnt/rootfs

mount -o bind /dev /mnt/rootfs/dev
mount -t devpts devpts /mnt/rootfs/dev/pts
mount -t sysfs sys /mnt/rootfs/sys
mount -t proc proc /mnt/rootfs/proc

exec switch_root /mnt/rootfs /sbin/init
