[general]
aports_branch = edge
aports_cache_dir = %(workdir)s/cache_aports
build_device = device/oneplus-enchilada
ui = phosh

[install]
device = google-oriole
flavor = mobile
extra_packages_file = %(basedir)s/packages.list
